export const HERO_DEPTH_TRANSITION_START = 0.9;
export const HERO_DEPTH_TRANSITION_END = 1;
export const STATS_CAMERA_MOTION_END = 0.88;
export const NEXT_SECTION_INTERNAL_ANIMATION_TRIGGER = 0.49;
export const NEXT_SECTION_COUNTER_TRIGGER = 0.58;
