export const SERVICES_TITLE_REVEAL_DISTANCE = 160;
export const SERVICES_CARD_REVEAL_DISTANCE = 320;
export const SERVICES_CARD_REVEAL_DISTANCE_COMPACT = 180;
export const SERVICES_CARD_REVEAL_OVERLAP = 42;
